services:
  - name: schedulink-api
    type: web
    env: node
    plan: starter
    # Backend service runs from repository root so shared root package.json build/start scripts work.
    # buildCommand builds the frontend (for optional static serving) but primary static site is separate.
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeploy: true
    # Health check uses /health (alias to /api/health in server). Standardization to /api/health is optional later.
    healthCheckPath: /health
    envVars:
      - key: ENFORCE_HTTPS
        value: "true"
      - key: CSP_STRICT
        value: "true"
      - key: PRINT_SECRET_FINGERPRINTS
        value: "false"
      # Secrets and runtime credentials are NOT stored in the blueprint. Use dashboard or env sync scripts.

  - name: schedulink-app
    type: static
    rootDir: testapp
    buildCommand: npm ci && npm run build
    publishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_GOOGLE_CLIENT_ID
        value: "placeholder"
    # NOTE: For client-side routing add a rewrite in dashboard Settings -> Redirects/Rewrites:
    # /*  /index.html  200  (Render currently doesn't support SPA fallback in blueprint)
