services:
  - name: diyartec-api
    type: web
    env: node
    plan: starter
    rootDir: .
    buildCommand: npm ci && npm run build:api
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: ENFORCEHTTPS
        value: "true"
      - key: CSPSTRICT
        value: "true"
      - key: PRINT_SECRET_FINGERPRINTS
        value: "false"
      - key: HSTSENABLED
        value: "true"
      - key: SECURITYHEADERSENABLED
        value: "true"
      - key: RATELIMIT_ENABLED
        value: "true"
      - key: CSRFPROTECTION_ENABLED
        value: "true"
      # Secrets & credentials are not embedded; sync via dashboard or automation scripts.

  - name: diyartec-app
    type: static
    rootDir: testapp
    buildCommand: npm ci && npm run build
    publishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_GOOGLE_CLIENT_ID
        value: "placeholder"
    # Add SPA rewrite in dashboard if deep links 404:
    # /*  /index.html  200
